platform :ios, '8.0’

target ‘ZXDemo’ do


#pod 'JPush'
pod 'MJRefresh'
pod 'Masonry'
pod 'AFNetworking'
pod 'SDWebImage'
pod 'SDWebImage/GIF'
pod 'DFPlayer'
pod 'ZFPlayer', '~> 3.0'
pod 'ZFPlayer/ControlView', '~> 3.0'
pod 'ZFPlayer/AVPlayer', '~> 3.0'
pod 'GPUImage'
pod 'WMPageController'
end
